- name: Install concourse
  become: true
  hosts: all
  tasks:
    - name: get concourse-ci
      get_url:
        url: https://concourse-ci.org/docker-compose.yml
        dest: .

    - name: change EXTERNAL_URL
      replace:
        path: ./docker-compose.yml
        regexp: 'http://localhost:8080'
        replace: 'http://localhost:38080'

    - name: insert proxy
      lineinfile:
        dest: ./docker-compose.yml
        line: "{{item}}"
      with_items:
        - "      http_proxy: {{ansible_env.http_proxy}}"
        - "      https_proxy: {{ansible_env.https_proxy}}"
        - "      no_proxy: {{ansible_env.no_proxy}}"
        - "      HTTP_PROXY: {{ansible_env.http_proxy}}"
        - "      HTTPS_PROXY: {{ansible_env.https_proxy}}"
        - "      NO_PROXY: {{ansible_env.no_proxy}}"
        - "      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: 'true'"
        - "      CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE: 'true'"
      when:
        - ansible_env.http_proxy is defined
        - ansible_env.https_proxy is defined
        - ansible_env.no_proxy is defined

    - name: Run concourse
      docker_compose:
        project_src: ./
        state: present

    - name: wait for started concourse
      uri:
        url: "http://localhost:8080/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    - name: get fly-cli
      get_url:
        url: http://localhost:8080/api/v1/cli?arch=amd64&platform=linux
        dest: /usr/local/bin/fly
        mode : 0755
