- name: Install concourse
  become: true
  hosts: all
  tasks:
    - name: get concourse-ci
      get_url:
        url: https://concourse-ci.org/docker-compose.yml
        dest: .

    - name: change EXTERNAL_URL
      replace:
        path: ./docker-compose.yml
        regexp: 'http://localhost:8080'
        replace: 'http://localhost:38080'

    - name: insert proxy
      lineinfile:
        dest: ./docker-compose.yml
        line: "{{item}}"
      with_items:
        - "      http_proxy: {{ansible_env.http_proxy}}"
        - "      https_proxy: {{ansible_env.https_proxy}}"
        - "      no_proxy: {{ansible_env.no_proxy}}"
        - "      HTTP_PROXY: {{ansible_env.http_proxy}}"
        - "      HTTPS_PROXY: {{ansible_env.https_proxy}}"
        - "      NO_PROXY: {{ansible_env.no_proxy}}"
        - "      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: 'true'"
        - "      CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE: 'true'"

    - name: Run concourse
      docker_compose:
        project_src: ./
        state: present

    - name: Wait for listened port
      wait_for:
        port: 8080

    - name: get fly-cli
      get_url:
        url: http://localhost:8080/api/v1/cli?arch=amd64&platform=linux
        dest: /usr/local/bin/fly
        mode : 0755
